name: habr_app
description: Habr application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:

    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: "^0.16.1"
  cupertino_icons: ^0.1.3
  http: ">=0.12.0"
  equatable: ">=0.1.1"
  html: "0.14.0+3"
  share: "0.6.5"
  flutter_highlight: "0.6.0"
  either_dart: ">=0.0.5"
  flutter_svg: "^0.19.0"
  url_launcher: "^5.6.0"
  moor_flutter: ^3.1.0
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  flutter_slidable: 0.5.4
  flutter_mobx: ^1.1.0+2
  photo_view: ^0.10.2
  path_provider: ">=1.6.22"
  crypto: ">=2.1.5"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"
  moor_generator: ^3.1.0
  hive_generator: ^0.7.2+1
  build_runner: ^1.8.1
  mobx_codegen: ^1.1.1+1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/ufo.png
    - assets/images/default_avatar.svg
    - assets/images/empty_comments.svg
    - assets/images/background.png
    - assets/images/lot_of_entropy.webp
    - assets/images/resolved.webp
    - assets/images/fatal_error.webp


