name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.3'
        channel: 'stable'
    - name: fix
      run: flutter clean
    - name: Install dependencies
      run: flutter pub get
    - name: Codegen
      run: |
        flutter pub run build_runner build
    - name: Build apk
      run: |
        flutter build apk --split-per-abi
    - name: Make zip with apks
      run: |
        cd build/app/outputs/apk/release
        zip apk.zip app-arm64-v8a-release.apk app-armeabi-v7a-release.apk app-x86_64-release.apk
    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: build/app/outputs/apk/release/apk.zip
  deploy:
    runs-on: ubuntu-latest

    if: github.ref != 'refs/heads/master'
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: apk
      - name: Log files
        run: echo $(ls)
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.1
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./apk.zip
          asset_name: apk.zip
          asset_content_type: application/zip

