name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
#     - name: Run tests
#       run: pub run test
    - name: Build apk
      run: flutter build apk --split-per-abi
    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: build/app/outputs/apk/release
