name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20.2'
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
#     - name: Run tests
#       run: pub run test
    - name: Build apk
      run: flutter build apk --split-per-abi
    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: build/app/outputs/apk/release
  deploy:
    runs-on: ubuntu-latest

#    if: github.ref != 'refs/heads/master'
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: apk
      - name: Log files
        run: ls
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.1
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./apk
          asset_name: apk.zip
          asset_content_type: application/zip

